### ISSUE TITLE
Hardware inventory in Linux: passwordless execution needed for certain commands 

### ISSUE THREAD

**Issue by bforesman** [device42/nix_bsd_mac_inventory#10]
The program froze while gathering hard disk information in Ubuntu 16.04 LTS, due to the **hdparm** and **fdisk** programs needing passwordless execution as root.  The README only suggests doing this for **dmidecode**.  I fixed this by adding:

*%\<user-group-here\> ALL = (ALL) NOPASSWD:/usr/sbin/dmidecode,/sbin/hdparm,/sbin/fdisk*

to **/etc/sudoers**, which allowed all HDD information to be retrieved.

I'm not sure if this should be an update README branch, or something else.

**Comment by rickjohnston** [comment]
Thanks for pointing that out. We have updated the README.
