### ISSUE TITLE
Hardware associated with a Device uploads unattached to Device

### ISSUE THREAD

**Issue by bforesman** [device42/nix_bsd_mac_inventory#11]
Hard discs in a desktop running Ubuntu 16.04 LTS (the device) are created as isolated "Parts" and "Parts Models" in device42, and are not automatically associated with the device itself.  They cannot be viewed in the device's page in the web UI.  Setting **add_hdd_as_device_properties= True** in *inventory.cfg* does not resolve the issue.  Likewise setting **add_hdd_as_parts = False** does not resolve the issue.

**Comment by rickjohnston** [comment]
Sorry for late reply, but this fixed in this commit: https://github.com/device42/nix_bsd_mac_inventory/commit/c7fffd2baa2e426c43f53c6b50a64fd85fb00e48
