### ISSUE TITLE
[feature request] gather hardware disk info behind raid controllers 

### ISSUE THREAD

**Issue by smithian** [device42/nix_bsd_mac_inventory#15]
It would be great if this could interrogate the system to determine which disks are provided by raid controllers, and attempt to gather data on the physical disks from them, either from manufacturer specific tools like megacli, hpssacli, omconfig, etc. or through smartmontools.

**Comment by davidgarvey** [comment]
Humm,

I have done that for linux boxes... linux module added this. It update a custom field in d42.

    def get_hdd(self):
        megaraid = "ls /opt/MegaRAID/MegaCli/MegaCli64"
        data, data_err = self.execute(megaraid, True)
        if not data_err:
            hw_hdds = self.get_hwraid()
            self.devargs.update({'hddcount': hw_hdds})

        else:
            hdds = self.get_hdd_names()
            hw_hdds = [x for x in hdds if '/mapper' not in x]
            if hw_hdds:
                if self.add_hdd_as_devp :
                    self.devargs.update({'hddcount': len(hw_hdds)})
                for hdd in hw_hdds:
                    hdd_part = self.get_hdd_info_hdaparm(hdd)
                    if hdd_part:
                        self.hdd_parts.append(hdd_part)

    def get_hwraid(self):

        raid_level = "/opt/MegaRAID/MegaCli/MegaCli64 -ldinfo -lALL -aALL | awk '/^RAID Level/{print $4}' | grep -Po '\d'"
        raid, error = self.execute(raid_level, True)
        raid = raid[0].rstrip('\n')
        if not error:
            # This has to be updated first hddraid_type
            self.devargs.update({'hddraid_type': 'raid ' + raid})

        else:
            print error

        cmd = "/opt/MegaRAID/MegaCli/MegaCli64 -pdlist -aALL | grep 'Slot Number' | wc -l"
        hdd_count, data_err = self.execute(cmd, True)
        hdd_count = hdd_count[0].rstrip('\n')
        if not data_err:
            cmd = "ls /dev/nvme[0-4]"
            nvme_list, err = self.execute(cmd, True)
            if not err:
                nvme_count = len(nvme_list)
                hdd_count = nvme_count + int(hdd_count)
            return hdd_count
        else:
            print data_err


And added a custom field uploader to get the data about disks into the database.

    def put_custom_field(self, data):
        print "Here in put_device:%s" %data
        if not DRY_RUN:
            url = self.base_url + '/api/1.0/device/custom_field/'
            msg = '\r\nUpdating device by mac %s ' % url
            if self.debug:
                print msg
            method = 'put'
            result, scode = self.uploader(data, url, method)
            return result, scode

**Comment by rickjohnston** [comment]
Hi David,

Thanks for sharing. The command and command path is too restrictive for a larger audience and not sure if that merge worthy in the main codebase. But this will be useful for anybody who wants to extend the script to get the RAID level data. 

Regards,
Rick
