### ISSUE TITLE
Linux Auto-discovery not discovering services and application

### ISSUE THREAD

**Issue by akashsarpate** [device42/nix_bsd_mac_inventory#19]
We tried to run main.py script to discover linux servers but it seems that it's not discovering applications and services on that server, can you please let us know parameter name to include in inventory.cfg file so that it will discover application and services.
When we did using consol(UI), checked option Discover Applications/Discover Services option it working.
We want to do same using script so please provide parameter to include in inventory.cfg file.

**Comment by bearburger** [comment]
Hello, @akashsarpate 

We don't support services and applications discovery in this tool. As an alternative I'd recommend you to try [Windows based Auto Discovery Software](https://www.device42.com/autodiscovery/) or [Linux-based Auto Discovery Software](https://www.device42.com/autodiscovery/). 

But I think the simplest way to discover services and applications would be *nix auto-discovery from the Device42 UI

![image](https://user-images.githubusercontent.com/634114/37391232-9d5836ba-277b-11e8-95d2-485673b35286.png)

**Comment by akashsarpate** [comment]
yes we already tried using UI it's working but we want to do it using script.
Is there any option available ?

**Comment by jaylomax** [comment]
@akashsarpate I am from the support team at Device42. Can you please reach out to me at jason.lomax@device42.com so we can assist.

**Comment by akashsarpate** [comment]
jason, as mentioned above  i am using Linux-based Auto Discovery Software and it's working as per my requirement. thanks for help
