### ISSUE TITLE
issues with module_linux

### ISSUE THREAD

**Issue by davidgarvey** [device42/nix_bsd_mac_inventory#20]
I am having issues with a linux vendor box that doesn't like the way commands are found. the remote inventory script work fine on other linux boxes. however, when I run it against the vendor linux it drops the ssh connection.

the code in question is the way command are discovered.

commands = ['cat /dev/null',
           'dmidecode -V',
           'fdisk -V',
            'find --version',
            'grep -V',
            'hdparm -V',
            'hostname',
            'id',
            'ifconfig -V',
            'ip -V',
            'lshal -V'
            'python2 -h',
            'python3 -V',
            'sort --version'
            'sudo -V',
            'wc --version']  

It iterates though all the likely bin directories looking for a match? It is this trail and error which is I believe is causing the OS to drop the ssh connection. 

    def get_cmd_paths(self):
        search_paths = ['/usr/bin', '/bin', '/usr/local/bin', '/sbin', '/usr/sbin', '/usr/local/sbin']
        for cmd_to_find in commands:
            for search_path in search_paths:
                cmd_path = "%s/%s" % (search_path, cmd_to_find)
                data_out, data_err = self.execute(cmd_path, False)
                print "Here is data_out:%s, %s" %(data_out,data_err)
                if not data_err:
                    self.paths.update({cmd_to_find.split()[0]: search_path})
                    break
                if 'command not found' in data_err:
                    if self.debug:
                        print '\t[-] Failed to find command "%s" at path "%s"' % (cmd_to_find, search_path)

Has anyone written this to use the "which" command for command discovery?

**Comment by davidgarvey** [comment]
well thats not the issue, I am have written past that and still have the error. it must be something else?

(1, 'Administratively prohibited')

**Comment by davidgarvey** [comment]
I am going to have to contact the vendor on this box. ssh works different.

**Comment by rickjohnston** [comment]
Thanks David. We will leave it open for a few days. Please let us know if that is an issue within the codebase or you are able to resolve it with the vendor.

**Comment by davidgarvey** [comment]
Yeah, it looks like if I slow down the execution of the commands I am able to get it work.

thanks
David
