### ISSUE TITLE
threads sometimes hang on ssh.connect()

### ISSUE THREAD

**Issue by rickvaughn** [device42/nix_bsd_mac_inventory#3]
When running network discovery across our subnet, using ssh key auth, I've found that the thread hangs on certain hosts and never times-out or throws any exception.  After a bit of digging I found out that it is hanging on our ssh enabled APC devices.  Looks to be an issue with the paramiko module itself, but perhaps there's some mitigation that can be applied.  Anyone else run into this issue?

**Comment by dejanlevaja** [comment]
Hello,
Sorry for the delay. I have tested the issue you're having with APC but I cannot confirm. 
In my case, both user/pwd and key access do time out and the script exits as expected. I have also scanned a range of IPs including some APC PDUs to see if the script hangs in case when we scan more that few IPs, but it all went OK again.
Can you share the APC SSH settings?

Thanks

**Comment by rickrdvaughn** [comment]
Oops apparently I forgot to subscribe to this for notifications.  Did a little more digging and it looks like it's actually not the APC units.  The ones I'm seeing this behavior on are TrippLite: PDU3VS6L2130

**Comment by rickjohnston** [comment]
Hi,

We have added exclude_ips as an option in the config file that will help with this issue.

Thanks.

**Comment by rickrdvaughn** [comment]
Excellent.  Thanks!
